baseURL = "http://10.0.0.3:1313"
languageCode = "en-us"
title = "VasilRYordanov"

canonifyurls = true

author = "Vasil R Yordanov"
theme = "black-and-light"

pygmentscodefences = true
summaryLength = 50
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['$', '$'], ['\\(', '\\)']]

[params]
  sitename = "Vasil Radkov Yordanov"
  disableWebFonts = false
  description = "My personal website, where I share thoughts about conferences I attend, papers and books I read, physics, philosophy, cinema, and open-source projects."

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 2

# [[menu.main]]
#     name = "Research"
#     url = "/research/"
#     weight = 3

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 5

[frontmatter]
  date = ['date', 'publishdate', 'pubdate', 'published', 'lastmod', 'modified']
  expiryDate = ['expirydate', 'unpublishdate']
  lastmod = [':git', 'lastmod', 'modified', 'date', 'publishdate', 'pubdate', 'published']
  publishDate = ['publishdate', 'pubdate', 'published', 'date']
