baseURL = 'https://landflier.cloud/'
languageCode = 'en-us'
title = 'VasilRYordnov'

canonifyurls = true

author = "Vasil R Yordanov"
theme = "black-and-light"

# pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Vasil Radkov Yordanov"
  disableWebFonts = false
  description= "My perosnal website, where I share thoughts about conferences I attend, papers and books I read, physics, philisophy, cinema, and open-source"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4
