baseURL = 'https://landflier.cloud/'
languageCode = 'en-us'
title = 'VasilRYordnov'

canonifyurls = true

author = "Vasil R Yordanov"
theme = "black-and-light"

# pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Vasil Radkov Yordanov"
  disableWebFonts = false
  description= "My perosnal website, where I share thoughts about conferences I attend, papers and books I read, physics, philisophy, cinema, and open-source"

[[menu.main]]
    name = "About"
[[menu.main]]
    name = "Research"
[[menu.main]]
    name = "Blog"
[[menu.main]]
    name = "Projects"
